name: My Action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f2003853@ds.study.iitm.ac.in
        run: echo "Hello, world!"
       
      - name: Fetch ISS location data
        run: | # python
          uv run --with requests python << 'EOF'
          import requests