name:  23f2003853@ds.study.iitm.ac

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 10:00 AM UTC
  workflow_dispatch:  # Allows for manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0  # Ensures the full commit history is fetched

      # Step 2: Configure Git with your username and email
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "23f2003853@ds.study.iitm.ac.in"

      # Step 3: Ensure changes are made to daily_commit.txt
      - name: Ensure changes are made
        run: |
          # Create or update the file with the current date
          echo "This is a daily commit - $(date)" >> daily_commit.txt
          git add daily_commit.txt
          git diff --cached || exit 0  # Exit if no changes

          # Commit and push changes
          git commit -m "Daily commit - $(date)" || exit 0  # Skip if no changes

      # Step 4: Push the commit
      - name: Push changes
        uses: ad-m/github-push-action@v0.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  # Ensure you're pushing to the correct branch
          force: true  # Optional: Force push to avoid errors

